<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->get() as $item){
            DB::table('products')->insert([
                'id' => $item['id'],
                'category_id' => $item['category_id'],
                'title' => $item['title'],
                'description' => $item['description'],
                'price' => $item['price'],
                'image' => $item['image'],
                'one' => $item['one'],
                'visible' => 1
            ]);
        }
    }

    private function get()
    {
        $products = array(
            array(
                "id" => 1,
                "category_id" => 1,
                "title" => "Glaïeul",
                "description" => "Le genre comprend 180 espèces La plupart des glaïeuls que nous connaissons sont des hybrides d'espèces sud-africaines. On distingue - les glaïeuls hybrides à grandes fleurs, espèces vigoureuses à tige rigide poussant jusqu'à 1,50m - les glaïeuls hybrides à petites fleurs (ou glaïeul papillon) ont des fleurs majestueuses portant en général des taches de couleurs vives contrastant avec les pétales inférieurs, tendant à évoquer un papillon. - Primulinus gladiolus est une variété particulière de glaïeul dont le pétale supérieur recouvre le pistil et les étamines de la fleur à la manière d'un petit capuchon protecteur, rendant le cœur de la fleur difficile à voir. - Glodiolus colvillei et Gladiolus nanus, sont très proches, ils sont le résultat d'un croisement entre des espèces d'été et d'hiver. Ces fleurs se déclinent en blanc, saumon ou même rouge.\r\n",
                "price" => 9.9900,
                "image" => 'products/01.jpg',
                "one" => 1,
            ),
            array(
                "id" => 3,
                "category_id" => 1,
                "title" => "Aubépine",
                "description" => "Le genre comprend plus de 200 espèces - Crataegus laevigata l'espèce type - Crataegus laevigata 'Alba Plena' aux fleurs doubles blanches - Crataegus laevigata 'Paul's Scarlet' aux fleurs doubles rouges - Crataegus laevigata 'Crimsom Cloud' aux fleurs rouges et blanches en leur centre (cf photo)\r\n\r\n",
                "price" => 20.2600,
                "image" => 'products/03.jpg',
                "one" => 1,
            ),
            array(
                "id" => 11,
                "category_id" => 1,
                "title" => "Lupin",
                "description" => "Le lupin étonne toujours avec ses hampes florales dressées couvertes de fleurs et son feuillage découpé très original. Il existe deux grandes catégories : les lupins vivaces, dont le fameux Lupin polyphylle et les lupins annuels, comme le lupin changeant, le lupin de Hartweg ou le lupin grand. Il existe aussi une espèce arbustive, le lupin en arbre qui forme une boule de 1,5 mètre qui se couvre de grappes de fleurs jaunes à la fin du printemps. Vous pouvez planter le lupin de manière isolé sur votre pelouse ou il sera ainsi mis en valeur, ou le mettre en place dans un massif. De toute les façon, méfiez-vous car il peut vite devenir envahissant car il se ressème tout seul ! Le lupin doit être semé directement en place, car il supporte mal le repiquage. Installez-le avec des roses trémières, ils cohabiteront très bien et ne demanderont guère d'entretien. Coupez les hampes des qu'elles sont fanées, ainsi il remontera à l'automne. Notez que les lupins vivaces finissent par dépérir au bout de 3-4 ans.\r\n\r\n\r\n",
                "price" => 10.0000,
                "image" => 'products/11.jpg',
                "one" => 1,
            ),
            array(
                "id" => 12,
                "category_id" => 1,
                "title" => "Bleuet vivace",
                "description" => "lot de 12 pieds \r\nFamille : Astéracées\r\nOrigine : Europe\r\nPériode de floraison : d'avril à août\r\nCouleur des fleurs : bleu, blanc, rose\r\nExposition : soleil\r\nType de sol : ordinaire à pauvre, bien drainé\r\nAcidité du sol : neutre, calcaire accepté\r\nHumidité du sol : normal\r\nUtilisation : massif, bordure, fleurs coupées, fleurs séchées\r\nHauteur : de 50 à 1 m selon les variétés\r\nType de plante : fleur\r\nType de végétation : vivace, il existe des espèces annuelles\r\nType de feuillage : persistant\r\nRusticité : rustique\r\nPlantation, rempotage : printemps\r\nMéthode de multiplication: semis au printemps et mise en place à l'automne, division de la touffe\r\nTaille : -\r\nEspèces, variétés intéressantes: Espèces vivaces\r\n- Centaurea alpestris aux fleurs roses\r\n- Centaurea dealbata fleurit à l'automne\r\n- Centaurea macrocephala fleurit jaune\r\n- Centaurea montana le bleuet des montagnes ou barbeau de montagne\r\n- Centaurea montana 'Alba' variété aux fleurs blanches\r\n- Centaurea montana 'Rosea' , variété aux fleurs roses\r\nMaladies et insectes nuisibles : le mildiou, la rouille, les pucerons\r\nToxicité : Les fleurs contiennent des substances digestives et diurétiques",
                "price" => 15.0000,
                "image" => 'products/12.jpg',
                "one" => 1,
            ),
            array(
                "id" => 13,
                "category_id" => 1,
                "title" => "Lavande",
                "description" => "lot de 3 pieds Famille: Labiées Origine: Bassin méditerranéen, îles Canaries, Afrique du nord, Inde, Asie du sud-est Période de floraison: de mai à août selon les variétés, fleurs parfumées et mellifère qui attirent les abeilles Couleur des fleurs: bleu, mauve, violet, blanc Exposition: plein soleil Type de sol: ordinaire, légère, drainé, voir pauvre Acidité du sol: neutre Humidité du sol: normal à sec Utilisation: massif, bordure, haie basse, talus, bac, fleurs coupées à prélever avant l'ouverture, pots-pourris Hauteur: de 30 à 100 cm selon les variétés Type de plante: arbrisseau Type de végétation: vivace Type de feuillage: persistant Rusticité: de -15 à -20°C pour les plus rustiques, Lavandula stoechas commence à souffrir à partir de -5°C, protéger les les Lavandes en pot Plantation, rempotage: printemps Méthode de multiplication: semis au printemps, bouturage en juillet-août en prélevant des rameaux de 5 cm que vous planterez dans une mini-serre Taille: Indispensable. Pratiquez une taille après la floraison pour lui garder sa forme ronde. En vieillissant, la lavande a tendance à se dégarnir à la base, surtout si elle n'a pas été régulièrement taillée. Mieux vaut dans ce cas, remplacer le pied, car une taille sévère ne donne rarement de bons résultats, les percements sur le vieux bois étant rares. Espèces, variétés intéressantes: Le genre comprend 28 espèces - Lavandula angustifolia ou Lavandula officinalis est la Lavande vraie ou fine, elle mesure de 1 à 1,20 m. Il existe de très nombreux cultivars comme 'Edelweiss' à fleurs blanches. De sa distillation, on obtient l'huile essentielle lavande fine AOC qui est recherchée par les parfumeurs. - Lavandula dentala, la Lavande anglaise est une espèce assez frileuse - Lavandula latifolia, la lavande aspic au parfum camphré est peu cultivée en France - Lavandula stoechas, la lavande à toupet ou lavande maritime est originaire du Portugal, elle fleurie de mai à juillet, ses fleurs sont surmontées de bractées violettes - Lavandula stoechas peduncalata, la Lavande papillon a un port plus érigé que l'espèce type, c'est la plus cultivée. Elle fleurie d'avril à juin - Lavandula 'Blue scent' , une nouveauté qui fleurit abondamment dès la première année de plantation - Lavandula latifolia X lavandula angustifolia est le lavandin qui est très florifères et rustique. Sa production est essentiellement utilisée dans la savonnerie Maladies et insectes nuisibles: le botrytis Toxicité: La lavande est connue depuis la nuit des temps pour son parfum et ses propriétés apaisantes et antiseptiques.",
                "price" => 10.0000,
                "image" => 'products/13.jpg',
                "one" => 1,
            ),
            array(
                "id" => 33,
                "category_id" => 1,
                "title" => "Rosier",
                "description" => "Les roses au jardin, quel bonheur ! Voici comment réussir la culture des rosiers : de la plantation à l'entretien, en passant par les différentes formes de rosiers et leur utilisation au jardin.\r\n\r\nLe rosier, un arbuste facile à vivre aux multiples facettes\r\n\r\nS'il est un arbuste à fleurs incontournable au printemps et en été, c'est bien le rosier (genre : Rosa, famille des Rosacées) ! Ou plutôt, les rosiers : il en existe de toutes les tailles (de quelques dizaines de centimètres de haut à plusieurs mètres), pour tous les usages (en isolé sur une pelouse, dans un massif, en bordure, comme couvre-sol, en pot, pour habiller une clôture, une façade, une pergola...), de presque toutes les couleurs, parfumés ou non, avec des roses de formes variées... Le plus difficile sera sans doute de le choisir ! Car une fois planté et bien installé, à part des tailles régulières et la surveillance de quelques maladies, votre rosier vous demandera assez peu d'entretien et il fleurira généreusement, année après année.\r\n\r\n\r\n",
                "price" => 29.9500,
                "image" => 'products/rose-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 39,
                "category_id" => 1,
                "title" => "Lys",
                "description" => "De culture très facile, le lis, ou lys, séduit par sa floraison spectaculaire et ses multiples couleurs. Faites-lui une place au jardin, ou réservez-lui un pot, il refleurira d'année en année sans soins particuliers.\r\n\r\nSa majesté le lis\r\n\r\nLe lis, ou lys, est une plante herbacée vivace à bulbe, appartenant au genre Lilium, qui compte de très nombreuses espèces et hybrides. Ses grandes fleurs majestueuses, bien connues des fleuristes, sont souvent divinement parfumées et offrent une grande diversité de teintes, du blanc le plus pur au rouge sombre, en passant par le jaune, le rose, le mauve, l'orange. Le lys peut être tacheté, moucheté ou panaché chez certains hybrides.\r\n\r\n\r\n",
                "price" => 12.9900,
                "image" => 'products/lys-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 40,
                "category_id" => 1,
                "title" => "Agapanthe",
                "description" => "L'agapanthe est une plante vivace à bulbe qui offre dès le début de l'été de belles et grosses fleurs bleues ou blanches. Elle a besoin d'un climat doux pour prospérer en pleine terre ; à défaut, on la cultivera en pot.\r\n\r\nUne bulbeuse à floraison estivale\r\n\r\nL'agapanthe (genre Agapanthus), ou tubéreuse bleue, est une plante bulbeuse originaire d'Australie et d'Afrique du Sud, appartenant à la famille des Liliacées. Les inflorescences en ombelles de 15 à 20 cm de diamètre, portées par des hampes florales qui peuvent atteindre un mètre de hauteur, ne passent pas inaperçues. Quant au feuillage, dense et rubané, il peut être vert ou panaché, et il apporte de la matière aux massifs et aux bordures du printemps à l'automne (selon les espèces, il est caduc ou semi-persistant).\r\n\r\n\r\n",
                "price" => 2.9500,
                "image" => 'products/agapanthe-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 5,
                "category_id" => 2,
                "title" => "Cyclamen de Perse",
                "description" => "Le cyclamen appartient à la même famille que les primevères (primulacées). En Europe, on trouve à l'état sauvage le Cyclamen europaeum, caractéristique de la flore des vallées alpines, et le cyclamen de Naples (Cyclamen hederifolium). Le cyclamen d'appartement est le Cyclamen persicum, originaire d'Europe Centrale et du bassin méditerranéen. Les variétés modernes peuvent fleurir pendant presque toute l'année et sont proposées de septembre à mars. Ces nouvelles variétés sont également plus résistantes à la chaleur.\r\n\r\n",
                "price" => 12.5900,
                "image" => 'products/05.jpg',
                "one" => 1,
            ),
            array(
                "id" => 35,
                "category_id" => 2,
                "title" => "Chrysanthème",
                "description" => "Souvent considéré comme la «marguerite des morts», le chrysanthème est trop peu présent dans les jardins. Pourtant, ces soleils multicolores rayonnent de tous les feux de l'automne, à une époque de l'année où les autres plantes s'effacent...\r\n\r\nPourquoi adopter le chrysanthème ?\r\n\r\nPalette de couleurs impressionnante, fleurs d'une multitude de formes : pompons, «japonais», simples, incurvées... Le genre chrysanthemum (famille des Asteracées) regroupe de nombreuses espèces de plantes vivaces très faciles à cultiver, dans laquelle chacun peut trouver son bonheur, et qui permet de garder un décor fleuri, au jardin comme sur les balcons, jusqu'à l'entrée de l'hiver.\r\n\r\n\r\n",
                "price" => 3.9900,
                "image" => 'products/chrysantheme-1.jpg',
                "one" => 0,
            ),
            array(
                "id" => 29,
                "category_id" => 3,
                "title" => "Camélia",
                "description" => "Le camélia est l’un des plus beaux arbustes à fleurs grâce à sa belle floraison, à l’automne ou au printemps.\r\n\r\n\r\n",
                "price" => 25.5000,
                "image" => 'products/camellia-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 36,
                "category_id" => 3,
                "title" => "Amarelys",
                "description" => "Un des bulbes vedettes, à la floraison spectaculaire quelques semaines seulement après sa mise en culture !\r\n\r\nL'amaryllis : un bulbe facile et spectaculaire\r\n\r\nOriginaires d'Amérique du Sud, les bulbes d'amaryllis (hippeastrum) sont aujourd'hui largement disponibles en jardinerie comme en grande surface au début de l'automne. Ils produisent de longues hampes, qui portent de grandes fleurs rouges, roses, orangées ou blanches en forme de trompette. Ces dernières s'ouvrent bien souvent avant l'apparition du feuillage.\r\n\r\n\r\n",
                "price" => 9.5500,
                "image" => 'products/amarylis-1.jpg',
                "one" => 0,
            ),
            array(
                "id" => 37,
                "category_id" => 3,
                "title" => "Pensée",
                "description" => "La pensée est une petite fleur dont les couleurs variées égayent de nombreux jardins et balcons, de l'automne jusqu'à l'été. Rustique, elle demande peu de soins et sa culture est aussi bien adaptée à la pleine terre qu'aux pots et jardinières.\r\n\r\nUne grande variété de couleurs tout au long de l'année\r\n\r\nLa pensée (Viola x wittrockiana) est une plante herbacée appartenant au genre Viola (famille des Violacées). Cousine de la violette, ses fleurs sont généralement petites, bien que certaines variétés offrent des fleurs de plus grande taille.\r\nElle peut être annuelle ou vivace (dans ce cas, elle est souvent cultivée comme bisannuelle), et se décline en une multitude de couleurs.\r\n\r\n\r\n",
                "price" => 1.9900,
                "image" => 'products/amarelys-3.jpg',
                "one" => 1,
            ),
            array(
                "id" => 38,
                "category_id" => 3,
                "title" => "Rose de noël",
                "description" => "Quelle meilleure période que le mois de décembre pour vous parler de la Rose de Noël, une des rares fleurs qui a le bon goût de fleurir à cette période de l'année ?\r\n\r\nUne floraison hivernale à découvrir\r\n\r\nLes Helleborus sont des plantes vivaces rhizomateuses appartenant à la famille des Renonculacées. Il en existe une quinzaine d’espèces, dont Helleborus niger, notre fameuse rose de Noël.\r\nElles sont originaires des régions méditerranéennes, mais on peut les trouver jusqu’à l’ouest de l’Asie.\r\n\r\nCe sont des plantes intéressantes en raison de leur feuillage et leur floraison originale qui intervient en hiver, période où les jardins sont assez dénudés. Leur hauteur généreuse (jusqu’à 70 cm) permet même à un léger manteau neigeux de composer un écrin à leur beauté.\r\nElles ont toutes en commun de former une touffe de jolies feuilles lobées ou palmilobées, coriaces et dentées sur leur pourtour dont la couleur peut varier du vert pâle au vert très foncé.\r\n\r\n\r\n",
                "price" => 4.9900,
                "image" => 'products/rosenoel-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 2,
                "category_id" => 4,
                "title" => "Abélia",
                "description" => " Le genre comprend plus de 30 espèces - Abelia chinensis, Abelia rupestris à privilégier dans les régions au climat doux, des petites feuilles en forme de coeur - Abelia x grandiflora (Abelia chinensis x Abelia uniflora), à la floraison abondante et délicatement parfumé - Abelia x grandiflora ‘Francis Mason' est un cultivar à feuillage marginé de jaune d'or et aux fleurs parfumées blanc rosé - Abelia x ‘Edward Goucher' , le plus petit pour les petits jardins - Abelia triflora, le plus grand et le plus parfumé - Abelia floribunda, a palisser au soleil - Abelia schumannii, plus rare\r\n\r\n",
                "price" => 50.5500,
                "image" => 'products/02.jpg',
                "one" => 0,
            ),
            array(
                "id" => 4,
                "category_id" => 4,
                "title" => "Crocus",
                "description" => "Le crocus, bien connu des jardiniers est une plante bulbeuse vivace à floraison printanière ou automnale selon les espèces. Ses fleurs unies, panachées, rayées ou encore dégradées peuvent se décliner en différentes couleurs. Dans les pelouses, le crocus se multiplie facilement et naturellement d'une année sur l'autre sans entretien particulier. Évitez simplement de lui couper les feuilles avant qu'elles ne soient fanées, il a besoin de restituer ses réserves après sa floraison. Quand le crocus est planté en groupe, il forme de magnifiques nuages de couleur dans les pelouses. Cette fleur se cultive également très bien en jardinière sur les balcons. Quelle que soit l'espèce, le bulbe appelé oignon présente 6 ou 7 feuilles pour 2 ou 3 pédoncules floraux.\r\n\r\n",
                "price" => 6.9900,
                "image" => 'products/04.jpg',
                "one" => 0,
            ),
            array(
                "id" => 10,
                "category_id" => 4,
                "title" => "Jacinthe",
                "description" => "N'hésitez à grouper de nombreux bulbes pour réaliser un bel effet, en les séparant d'une quinzaine de centimètres en tous sens. L'odeur des fleurs se remarque à plusieurs mètres. \r\n\r\nRetirez les bulbes une fois le feuillage séché, et laissez-les se reposer au frais avant de les replanter à l'automne suivante. Sachez que la floraison suivante sera de toute façon moins belle.\r\nPeut-on replanter un bulbe de jacinthe qui a été forcé à Noël ?\r\n\r\nJetez votre bulbe, il est épuisé !\r\nUn peu d'histoire...\r\n\r\n* La première Jacinthe est originaire de la région Est de la Méditerranée, selon la légende, c'est en Grèce qu'elle aurait été créée. Dans la mythologie, la Jacinthe serait née du sang de Hyacinthe, jeune homme tué par Zéphyr lors d'un lancer de disque. Apollon, peiné par cette tragédie, aurait faite naître une Jacinthe rouge du sang de Hyacinthe pour qu'il puisse revivre éternellement.\r\n* Pendant longtemps, ces jolies fleurs étaient associées à l'élégance, mais aujourd'hui la Jacinthe évoque avant tout l'insouciance, elle aussi symbole de la simplicité.",
                "price" => 9.9000,
                "image" => 'products/10.jpg',
                "one" => 1,
            ),
            array(
                "id" => 28,
                "category_id" => 4,
                "title" => "Rhododendron",
                "description" => "Le rhododendron est l'un des plus beaux arbustes de terre de bruyère. \r\n\r\nLa plantation, l'entretien et la taille; sont autant de gestes qui vous permettront d'améliorer la floraison et d'éviter les maladies.",
                "price" => 69.9000,
                "image" => 'products/rhododendron-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 31,
                "category_id" => 4,
                "title" => "Narcisse",
                "description" => "Les narcisses sont des plantes à bulbes très appréciées dans les jardins pour leur floraison printanière précoce. Facile à planter, le narcisse demande très peu d'entretien.\r\n\r\n\r\n",
                "price" => 2.9500,
                "image" => 'products/narcisse-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 32,
                "category_id" => 4,
                "title" => "Tulipe",
                "description" => "La tulipe, reine des fleurs à bulbe\r\n\r\nLa tulipe est l'une des fleurs les plus connues et les plus appréciées au printemps, aussi bien au jardin que sur une terrasse ou un balcon. Ses multiples couleurs et la simplicité de sa culture en font la reine des plantes à bulbe.\r\n\r\nHaute de 20 à 60 cm, la tulipe présente une grande diversité de formes et de couleurs, des plus pastel aux plus éclatantes (large palette de roses, de jaunes, d'orangés, de rouges, mais aussi blanc, bleu, violet, noir...). La tulipe est adaptée à tous les climats de France, et elle permet de réaliser très facilement de somptueuses compositions fleuries.\r\n\r\n\r\n",
                "price" => 2.9500,
                "image" => 'products/tulipe-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 34,
                "category_id" => 4,
                "title" => "Anémone",
                "description" => "Il existe un grand nombre d'espèces d'anémones, la plus connue étant sans doute l'anémone couronnée, aussi appelée anémone des fleuristes ou anémone des jardins. Cette plante à bulbe est appréciée pour ses fleurs colorées.\r\n\r\nL'anémone couronnée, une fleur à la fois sauvage et cultivée\r\n\r\nSes fleurs rouges, pourpres, bleues, roses ou blanches, qui s'épanouissent à la fin du printemps, sont adaptées aux bordures, aux rocailles, aux massifs et pourquoi pas aux jardinières. On peut aussi la couper pour confectionner des bouquets colorés et champêtres (lire aussi : Fleurs à couper pour beaux bouquets).\r\n\r\n\r\n",
                "price" => 12.5000,
                "image" => 'products/anemone-2.jpg',
                "one" => 1,
            ),
            array(
                "id" => 6,
                "category_id" => 5,
                "title" => "Palmier de Chine",
                "description" => "Le genre comprend 6 espèces - Trachycarpus fortunei 'Nanus' possède un tronc très court - Trachycarpus wagnerianus est une espèce que l'on trouve encore difficilement mais qui a bien des avantages pour nos régions et nos jardins; feuilles plus petites, très résistant au froid et au vent, convient bien aux bacs\r\n\r\n",
                "price" => 1051.0000,
                "image" => 'products/06.jpg',
                "one" => 1,
            ),
            array(
                "id" => 7,
                "category_id" => 5,
                "title" => "Olivier",
                "description" => "Le genre comprend une trentaine d'espèces. On estime qu’il existe plus de 2000 variétés sur le pourtour Méditerranéen. On peut greffer un olivier. - Olivier ‘Tanche’ => Bonne résistance au froid. Huiles et olives noires (généralement) - Olivier ‘Anglandau’ => Très bonne résistance au froid. Huiles et olives vertes (généralement) - Olivier ‘Bouteillan’ => Très bonne résistance au froid. Rendement intéressants. Huile. - Olivier ‘Cailletier’ => autofertile, plus de 90% des olives du département Alpes-Maritimes. - Olivier ‘Picholine’ => Petites Olives, la plus répandue en France.\r\n\r\n",
                "price" => 999.0000,
                "image" => 'products/07.jpg',
                "one" => 1,
            ),
            array(
                "id" => 8,
                "category_id" => 5,
                "title" => "Bananier du Japon",
                "description" => "On en rencontre de plus en plus dans nos jardins. C'est vrai qu'ils sont du plus joli effet isolé sur une pelouse grâce à leur feuillage original. Ils donnent une touche exotique et invitent au voyage.... Le Bananier du Japon est le plus rustique du genre, et il est possible d'envisager sa plantation un peu partout en France, pourvu que l'on protège le pied par un bon paillage dans les régions les plus froides. Sous les 0°C le feuillage disparaîtra et le stipe résistera plus ou moins en fonction de la rudesse de l'hiver. L'important est de protéger les rhizomes pour permettre au pied de redémarrer. En dehors des régions au climat doux, vous n'aurez guère de chance d'obtenir des fruits ! Apportez de l'engrais très régulièrement de l'engrais et de l'eau pendant les journées les plus chaudes, vous serez alors impressionné par la vitesse de sa croissance qui va jusqu'à produire une feuille par semaine.\r\n\r\n",
                "price" => 1500.0000,
                "image" => 'products/08.jpg',
                "one" => 1,
            ),
            array(
                "id" => 9,
                "category_id" => 5,
                "title" => "Sagine subulée hoéhoé",
                "description" => "La sagine subulée est une plante couvre-sol aussi appelée plante carpette ou gazonnante pour sa capacité à tapisser un sol grâce à ses racines traçantes. De faible hauteur, elle se développe jusqu'à former un tapis uniforme ressemblant à une moquette ne nécessitant pas d'être tondue. Elle est idéale pour compléter des espaces entre les dallages ou pour réaliser un jardin d'inspiration japonaise. Pour obtenir un tapis vert toute l'année, vous espacez les pieds de sagine d'une vingtaine de centimètres en tout sens dans un sol léger et frais. Elle n'apprécie guère la sécheresse et les piétinements réguliers.\r\n",
                "price" => 12.0000,
                "image" => 'products/09.jpg',
                "one" => 1,
            ),
            array(
                "id" => 30,
                "category_id" => 5,
                "title" => "Lilas",
                "description" => "A quoi rimerait le printemps si les effluves de lilas ne venaient pas chatouiller nos sens? Certainement à un jour sans soleil... Et puisque celui-ci daigne enfin faire son apparition, il est grand temps de s'intéresser à ces arbustes qui, à l'inverse des hirondelles, font le printemps.\r\n\r\n\r\n",
                "price" => 19.9900,
                "image" => 'products/lilas-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 41,
                "category_id" => 6,
                "title" => "Thuya",
                "description" => "Le thuya est un conifère ornemental très rustique, résistant à la sécheresse, fréquemment planté en haie. Ce grand arbre gagne cependant à être cultivé en isolé.\r\n\r\nUn grand arbre... bien peu adapté aux haies\r\n\r\nLe thuya appartient à la famille des Cupressacées. D’origine américaine ou asiatique selon les espèces, il est classé parmi les conifères et on le reconnaît aisément à son feuillage persistant vert ou doré, formé d’écailles imbriquées les unes dans les autres. Son port  conique, qui tend à devenir colonnaire chez les sujets âgés, est également très caractéristique.  Très rustique (il supporte des gelées de l’ordre de -20°C), peu exigeant, il nécessite un entretien minime.\r\n\r\n\r\n",
                "price" => 1200.0000,
                "image" => 'products/thuja-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 42,
                "category_id" => 6,
                "title" => "Weigelia",
                "description" => "Le weigelia est un arbuste dont la floraison abondante ne passe pas inaperçu au jardin. Vigoureux et de culture facile, il offre une profusion de fleurs en clochettes roses, rouges ou blanches, à la fin du printemps.\r\n\r\nUne floraison vigoureuse et remarquée\r\n\r\nQu'il soit planté en isolé ou sous forme de haie libre, Weigela florida est apprécié pour sa floraison généreuse et son développement vigoureux. Il atteint une hauteur de 1 à 2 mètres, et son feuillage, parfois panaché, est caduc. D'entretien facile, cet arbuste est très rustique et supporte des températures allant jusqu'à -20°C. Il résiste bien aux maladies et aux parasites.\r\n\r\n\r\n",
                "price" => 200.0000,
                "image" => 'products/weigela-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 43,
                "category_id" => 6,
                "title" => "Forsythias",
                "description" => "Qui ne connaît pas cet arbuste aux fleurs d'or ! Semblable à l'hirondelle, le forsythia annonce le printemps ! Rustique et flamboyant, il est de tous les jardins. Mais en réalité, sous ce nom se cache une belle gamme de variétés.\r\n\r\nForsythias, de l'or sur branches !\r\n\r\nOriginaires du Japon, de Chine, de Corée ou d'Albanie, les forsythias appartiennent à la même famille que le jasmin : les Oléacées. Selon les espèces et variétés, leur taille fluctue entre un mètre et 2,5 mètres, voire plus. Partant de la base, les rameaux dressés s'étalent pour leur donner une forme érigée, en boule ou même rampante.\r\n\r\nLes forsythias font partie des premiers arbustes à fleurir dans la saison; en effet, ils n'attendent guère le début du printemps pour se parer de leur magnifique floraison, alors que le feuillage en est encore absent. Les premières fleurs, d'un jaune plus ou moins vif, apparaissent fin février, notamment sur la variété F. ovata ‘Ottawa’, tandis que les dernières décorent les variétés tardives au mois d'avril. Les feuilles vertes et caduques n'apparaissent qu'ensuite et ne présentent guère d'intérêt, mises à part quelques rares exceptions.\r\n\r\n\r\n",
                "price" => 350.0000,
                "image" => 'products/gold-shrub-1.jpg',
                "one" => 1,
            ),
            array(
                "id" => 44,
                "category_id" => 6,
                "title" => "Pyracantha",
                "description" => "Pyracantha, communément appelé « buisson ardent » est un genre botanique de buissons persistants et épineux de la famille des Rosaceae, sous-famille des Maloideae. Le mot Pyracantha vient du grec Pyros, le feu et Acantha, l'épine.\r\n\r\nLe Pyracantha est originaire du sud de l'Europe et de l'Asie. Il peut atteindre 6 m de haut. C'est un proche parent du Cotonéaster, mais les Pyracanthas ont des feuilles dentelées coriaces de 2 à 4 cm de long et de grosses épines alors que le Cotoneaster n'en a pas.\r\n\r\nIls donnent, en fin de printemps, des fleurs blanches en corymbe donnant naissance à des pommettes rouge, orange, ou jaune mûres en automne.\r\n\r\n",
                "price" => 129.9000,
                "image" => 'products/firethorn.jpg',
                "one" => 1,
            ),
            array(
                "id" => 15,
                "category_id" => 7,
                "title" => "Cerises",
                "description" => "La cerise est le fruit comestible du cerisier. Il s'agit d'une drupe (petit fruit charnu à noyau), de forme sphérique, de couleur généralement rouge plus ou moins foncé, plus rarement jaune. Ce petit fruit compte environ 50 calories pour 100 grammes. La fleur est généralement blanche. ",
                "price" => 5.7500,
                "image" => 'products/cerises.jpg',
                "one" => 1,
            ),
            array(
                "id" => 17,
                "category_id" => 7,
                "title" => "Fraises",
                "description" => "La fraise est le fruit des fraisiers (Fragaria), herbacées de la famille des Rosaceae. Ce fruit est botaniquement parlant un faux-fruit puisqu'il s'agit en réalité d'un réceptacle charnu sur lequel sont disposés régulièrement des akènes dans des alvéoles plus ou moins profondes, la fraise étant donc un polyakène. \r\n\r\nL'espèce la plus consommée dans le monde est issue de l'espèce hybride Fragaria ×ananassa. Dans la suite de cet article, c'est généralement de cette espèce qu'il sera question sauf mention contraire.\r\n\r\nQuelques fruits d'autres espèces sans rapport avec Fragaria, et par analogie de forme, portent le nom vernaculaire de fraise.",
                "price" => 5.0000,
                "image" => 'products/fraises.jpg',
                "one" => 0,
            ),
            array(
                "id" => 18,
                "category_id" => 7,
                "title" => "Groseilliers",
                "description" => "Les groseilliers (genre Ribes) sont des arbustes de la famille des Grossulariacées, originaires des régions tempérées de l'hémisphère nord et de la Cordillère des Andes, dont plusieurs espèces sont cultivées pour leurs fruits diversement colorés tels que les groseilles et les cassis ou comme plantes ornementales. \r\n\r\nLa casseille résulte de l'hybridation entre le cassissier (ou groseillier noir) et le groseillier à maquereau.",
                "price" => 25.6000,
                "image" => 'products/groseillers.jpg',
                "one" => 1,
            ),
            array(
                "id" => 19,
                "category_id" => 7,
                "title" => "Mûres",
                "description" => "La mûre est le fruit du mûrier, arbre du genre Morus de la famille des Moracées, dont une espèce, Morus alba, le mûrier blanc, fut aussi beaucoup cultivée pour l'élevage du ver à soie qui se nourrit exclusivement de ses feuilles. Elle est comestible, riche en fibres alimentaires, riboflavine, magnésium et potassium et une très bonne source de vitamine C, vitamine K et de fer. \r\n\r\nLa mûre est un faux-fruit, composé de sortes de baies formées par le périanthe devenu charnu et portant un petit akène qui est le vrai fruit, et accolées les unes aux autres comme les fleurs sur l'épi. Ces fruits sont clairs ou foncés selon les espèces.\r\n",
                "price" => 16.8000,
                "image" => 'products/mures.jpg',
                "one" => 1,
            ),
            array(
                "id" => 20,
                "category_id" => 7,
                "title" => "Orange",
                "description" => "L’orange est un agrume, fruit des orangers, des arbres de différentes espèces de la famille des Rutacées ou d'hybrides de ceux-ci. Il en existe donc plusieurs types, principalement issus de l'espèce Citrus sinensis comme les oranges sanguines, et les oranges amères produites par le bigaradier. \r\n\r\nComestible, elle est très riche en vitamine C. C’est le quatrième fruit le plus cultivé au monde.",
                "price" => 0.8500,
                "image" => 'products/orange.jpg',
                "one" => 0,
            ),
            array(
                "id" => 21,
                "category_id" => 7,
                "title" => "Poires",
                "description" => "La poire est le fruit du poirier (Pyrus communis L.), arbre de la famille des Rosaceae, sous-famille des Maloideae, du genre Pyrus. Elle est communément verte, jaune ou rouge, avec quelques curiosités comme la très ancienne poire noire de Worcester. \r\n\r\nLa culture du poirier pour la production de fruits daterait de la Préhistoire, mais c'est à l'époque moderne, en Europe, que le fruit a été amélioré sous la forme que nous lui connaissons.",
                "price" => 1.3500,
                "image" => 'products/poires.jpg',
                "one" => 1,
            ),
            array(
                "id" => 25,
                "category_id" => 7,
                "title" => "Raisin blanc",
                "description" => "Le raisin est le fruit de la Vigne (Vitis). Le raisin de la vigne cultivée Vitis vinifera est un des fruits les plus cultivés au monde, avec 68 millions de tonnes produites en 2010, derrière les agrumes (124 millions), les bananes (102 millions) et les pommes (70 millions)1. Il se présente sous la forme de grappes composées de nombreux grains, qui sont sur le plan botanique des baies, de petite taille et de couleur claire, pour le raisin blanc (verdâtre, jaunâtre, jaune doré) ou plus foncée, pour le raisin rouge (mauve, rose ou noir-violet). \r\n\r\nIl sert surtout à la fabrication du vin à partir de son jus fermenté (on parle dans ce cas de raisin de cuve), mais il se consomme également comme fruit, soit frais, le raisin de table, soit sec, le raisin sec qui est utilisé surtout en pâtisserie ou en cuisine. On consomme également du jus de raisin. Des baies, on extrait aussi l'huile de pépins de raisin.",
                "price" => 3.5000,
                "image" => 'products/raisinblanc.jpg',
                "one" => 1,
            ),
            array(
                "id" => 27,
                "category_id" => 7,
                "title" => "Tomates",
                "description" => "La tomate (Solanum lycopersicum L.) est une espèce de plantes herbacées de la famille des Solanacées, originaire du nord-ouest de l'Amérique du Sud1, largement cultivée pour son fruit. Le terme désigne aussi ce fruit charnu. La tomate se consomme comme un légume, cru ou transformé. Elle est devenue un élément incontournable de la gastronomie de nombreux pays, et tout particulièrement dans le bassin méditerranéen. \r\n\r\nLa plante est cultivée en plein champ ou sous abri sous presque toutes les latitudes, sur une superficie d'environ trois millions d'hectares. La tomate a donné lieu au développement d'une importante industrie de transformation, pour la production de concentré, de sauces, notamment le ketchup, de jus et de conserves.\r\n\r\nL'espèce compte quelques variétés botaniques, dont la « tomate cerise » (mais la « tomate groseille » appartient à une espèce voisine, Solanum pimpinellifolium L.), et plusieurs milliers de variétés cultivées (cultivars).\r\n\r\nCompte tenu de son importance économique, elle est l'objet de nombreuses recherches scientifiques et est considérée comme une plante modèle en génétique. Elle a donné naissance à la première variété génétiquement transformée autorisée à la consommation et commercialisée de façon éphémère aux États-Unis dans les années 1990.",
                "price" => 1.3500,
                "image" => 'products/tomates.jpg',
                "one" => 1,
            ),
            array(
                "id" => 14,
                "category_id" => 8,
                "title" => "Aubergines",
                "description" => "L’aubergine (Solanum melongena L.) est une plante potagère annuelle de la famille des Solanacées, cultivée pour son fruit consommé comme légume. Le terme désigne aussi ce légume. ",
                "price" => 1.6000,
                "image" => 'products/aubergines.jpg',
                "one" => 1,
            ),
            array(
                "id" => 16,
                "category_id" => 8,
                "title" => "Citrouille",
                "description" => "La citrouille est une plante annuelle appartenant au genre Cucurbita et à la famille des Cucurbitaceae. C'est aussi le nom de son fruit volumineux, de couleur jaune orangé. \r\n\r\nUne citrouille peut atteindre 5 kg. La plus grosse du monde, venue de Napa, en Californie, fait 922 kg1. Elle sera exposée aux jardins botanique de New York dans le cadre de l'exposition d'Halloween de 2013. Le record précédent pesait 821 kg (record réalisé en 2010 par Chris Stevens, de New Richmond, Wyoming, États-Unis), alors qu'en Europe, la plus grosse citrouille ne pesait que 617 kg (elle a poussé pendant 129 jours et avec 1,5 tonne de fumier).",
                "price" => 1.2000,
                "image" => 'products/citrouille.jpg',
                "one" => 1,
            ),
            array(
                "id" => 22,
                "category_id" => 8,
                "title" => "Poivrons",
                "description" => "Le poivron (ou piment au Québec) est un groupe de cultivars de l'espèce Capsicum annuum (tout comme certains piments). Ce sont les variétés douces issues de cette espèce par sélection. Ces cultivars doux produisent des fruits de différentes couleurs dont le rouge, le jaune et l'orange. Le fruit est également consommé sous sa forme verte immature. C'est une plante annuelle de la famille des Solanacées originaire du Mexique, d'Amérique centrale et d'Amérique du Sud. La plante est cultivée comme plante potagère pour ses fruits consommés, crus ou cuits, comme légumes. Le terme désigne à la fois le fruit et la plante. \r\n\r\nLe poivron est l'ingrédient indispensable d'un certain nombre de plats, comme la piperade ou la ratatouille, mais il peut aussi bien servir d'accompagnement.\r\n\r\n",
                "price" => 2.3000,
                "image" => 'products/poivrons.jpg',
                "one" => 1,
            ),
            array(
                "id" => 23,
                "category_id" => 8,
                "title" => "Pomme de terre",
                "description" => "La pomme de terre, ou patate (langage familier, canadianisme et belgicisme), est un tubercule comestible produit par l’espèce Solanum tuberosum, appartenant à la famille des solanacées. Le terme désigne également la plante elle-même, plante herbacée, vivace par ses tubercules mais toujours cultivée comme une culture annuelle. La pomme de terre est une plante qui réussit dans la plupart des sols, mais elle préfère les sols légers légèrement acides. La plante est sujette aux maladies dans des sols calcaires ou manquants d’humus. \r\n\r\nLa pomme de terre est originaire de la cordillère des Andes dans le sud-ouest de l’Amérique du Sud où son utilisation remonte à environ 8 000 ans. Introduite en Europe vers la fin du xvie siècle à la suite de la découverte de l’Amérique par les conquistadors espagnols, elle s’est rapidement diffusée dans le monde et est en 2015 cultivée dans plus de 150 pays sous pratiquement toutes les latitudes habitées.\r\n\r\nEn fonction de son mode de cuisson, elle peut être une source importante de glucides, qui se présentent principalement sous forme de féculeN 1, mais aussi de protéines et de vitamines. Ses qualités nutritives et sa facilité de culture font qu’elle est devenue l’un des aliments de base de l’humanité : elle figure parmi les légumes et féculents les plus consommés et la principale denrée alimentaire non céréalière du monde. Cultivée et consommée localement, relativement peu commercialisée sur le marché mondial, elle est recommandée par l’ONU pour atteindre la sécurité alimentaire. C’est aussi la culture alimentaire la plus productive, produisant plus de matière sèche à l’hectare que les céréales, 85 % de la matière sèche produite par la plante étant comestible pour l’homme contre environ 50 % pour les céréales. Le rendement moyen est d’environ 17 tonnes à l’hectare au niveau mondial, mais se situe entre 40 et 50 tonnes dans certains pays développés d’Amérique du Nord et d’Europe occidentale. La pomme de terre reste sous-utilisée dans certains pays du Tiers Monde, notamment en Afrique sub-saharienne, mais globalement sa consommation progresse dans les pays en développement, tandis que dans les pays développés elle tend à diminuer, basculant de plus en plus vers des formes transformées (produits appertisés, déshydratés ou surgelés).\r\n\r\nLa fécule de pomme de terre a donné naissance à une industrie de transformation aux multiples débouchés dans les secteurs agro-alimentaire, cosmétique, pharmaceutique et industriel.\r\n\r\nCompte tenu de son importance économique, de nombreuses études scientifiques sur la pomme de terre et les espèces apparentées, notamment dans le domaine de la génétique, sont menées par des institutions publiques ou privées de différents pays, coordonnées au niveau mondial, entre autres, par le centre international de la pomme de terre.",
                "price" => 0.4500,
                "image" => 'products/pomme-de-terre.jpg',
                "one" => 1,
            ),
            array(
                "id" => 24,
                "category_id" => 8,
                "title" => "Radis",
                "description" => "Le radis, Raphanus sativus (du latin radix, radicis, « racine, raifort », du grec ῥαπυς, ῥαπυος, « rave, navet »), dit « ravanet » en provençal, est une plante potagère bisannuelle, de la famille des Brassicacées, cultivée pour son hypocotyle charnu, consommé cru, comme légume. Le terme désigne aussi le légume. La partie comestible, une racine pivot à chair blanche, est la partie gonflée, souterraine, de la tige, au-dessus de la racine. La peau du radis peut être de différentes couleurs, dont la plus courante est le rouge. Certaines variétés peuvent être à peau rose, blanche, ou gris-blanc.\r\n\r\n\r\n",
                "price" => 0.5000,
                "image" => 'products/radis.jpg',
                "one" => 1,
            ),
            array(
                "id" => 26,
                "category_id" => 8,
                "title" => "Salade",
                "description" => "La salade est un terme générique désignant en jardinage et horticulture diverses sortes de feuilles, c'est-à-dire de plantes potagères dont les feuilles, consommées crues, entrent dans la composition d'un mets froid dont elles ont pris le nom, la « salade », sous-entendu « salade verte ». Les salades sont des plantes angiospermes. \r\n\r\nCertaines se repiquent (chicorée, laitue), d'autres (mâche, pissenlit, roquette, pourpier) se sèment",
                "price" => 4.5000,
                "image" => 'products/salade.jpg',
                "one" => 1,
            ),
        );
        
        return $products;
    }
}
